### ISSUE TITLE
Slot in other parts of 13

### ISSUE THREAD

**Issue by brclar15** [hmteditors/hmt-13#2]
Need to properly slot in the other work that has been done on *Iliad* 13 in its proper places. Should all be kept in this repo

**Comment by StephanieML** [comment]
was this done?

**Comment by brclar15** [comment]
not entirely, the scholia collections need to be moved over, and reformatted to the .cex files. Pretty sure that they're all unique already though, so thats helpful

**Comment by StephanieML** [comment]
ok, I will do this today! THanks

**Comment by StephanieML** [comment]
looks like we were just missing the line and image indices so this is all done
